/** @jsxImportSource theme-ui */

import { makeStyles } from "@material-ui/core/styles";
const useStyles = makeStyles((theme) => ({
  BigContainer: {
    backgroundColor: "#fff",
    width: "300px",
    height: "315px",
    color: "#000",
    margin: "25px  30px 15px 45px",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    borderTopLeftRadius: "12px",
    borderBottomLeftRadius: "12px",
    borderTopRightRadius: "12px",
    borderBottomRightRadius: "12px",
    boxShadow: " rgba(149, 157, 165, 0.2) 0px 8px 24px",

    [theme.breakpoints.down("md")]: {
      margin: "5px 15px 15px 5px",
    },
    "&:hover": {
      boxShadow:
        "rgba(17, 17, 26, 0.1) 0px 4px 16px, rgba(17, 17, 26, 0.05) 0px 8px 32px",
      // boxShadow:" rgba(149, 157, 165, 0.2) 0px 8px 24px",
    },
  },
  TopBox: {
    width: "100%",
    position: "relative",
    [theme.breakpoints.down("md")]: {},
  },
  ImageStyles: {
    width: "100%",
    height: `147px`,
  },
  ImageStylesVector: {
    width: "25px",
    height: "15px",
    marginRight: 3,
    margin: "1px 0px 5px 0px",
  },
  BottomBox: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    padding: "0px 15px",
    // backgroundColor:"#ccc",
    [theme.breakpoints.down("md")]: {
      display: "flex",
      flexDirection: "column",
    },
  },

  BottomInFo: {
    height: "50%",
    // backgroundColor: '#eee',
    width: "98%",
    margin: "2px 1px",
    borderRadius: "6px",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
  },
  titlesPaper: {
    display: "flex",
    width: "100%",
    paddingLeft: 5,
    alignItems: "center",
    // backgroundColor: "#698",
    justifyContent: "space-between",
    backgroundColor: "transparent",
    [theme.breakpoints.down("md")]: {
      flexDirection: "row",
      alignItems: "center",
      height: "30px",
    },
  },
  F1C: {
    height: "28%",
    margin: "1px 0px 0px 0px",
    width: "100%",
    display: "flex",
    justifyContent: "space-Between",
    alignItems: "center",
    padding: "0px 10px",
    position: "relative",
  },
  F2C: {
    height: "38%",
    // backgroundColor: "#e47",
    margin: "1px 0px 0px 0px",
    width: "100%",
    fontSize: "16px",
    display: "flex",
    padding: "0px 5px 5px 15px",
    fontWeight: "400",
    flexDirection: "column",
  },
  F3C: {
    height: "33%",
    // backgroundColor: "#e47",
    margin: "8px 0px 0px 0px",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  RateBox: {
    width: 40,
    heigth: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  IconRate: {
    height: "100%",
    width: "100%",
    color: "gold",
  },
  TextRate: {
    color: "#fff",
    position: "absolute",
    fontSize: 10,
    fontWeight: "600",
    padding: 5,
  },

  Titre: {
    fontSize: "17px",
    fontWeight: "bold",
    margin: "5px 10px 5px 5px",
    zIndex: 20,
    [theme.breakpoints.down("md")]: {
      fontSize: "15px",
      margin: "5px 10px 5px 5px",
      fontWeight: "700",
    },
  },
  sousTitre: {
    fontSize: "16px",
    color: "#000",
    margin: "2px 0px 0px 5px",
    fontWeight: "400",
    [theme.breakpoints.down("md")]: {
      fontSize: "12px",
      width: "80%",
      margin: "2px 0px 0px -10px",
    },
  },
  Categorys: {
    fontSize: "12px",
    color: "#237a59",
    opacity: 0.6,
    padding: 5,
    overflow: "ellipsis",
    height: "20px",
    whiteSpace: "nowrap",
    textOverflow: "ellipsise",
    width: "410px",

    [theme.breakpoints.down("md")]: {
      fontSize: "10px",
      width: "100%",
      textOverflow: "ellipsis",
    },
  },
  Icon: {
    position: "absolute",
    top: 0,
    right: 0,
    color: "#fff",
    zIndex: 4,
    backgroundColor: "#087",
    width: "60px",
    height: "35px",
    outline: "none",
    cursor: "pointer",
    overflow: "hidden",
    borderRadius: "0px 0px 0px 8px",
    [theme.breakpoints.down("md")]: {
      fontSize: "10px",
      width: "40px",
      height: "35px",
    },
  },
  IconLeft: {
    cursor: "pointer",
    position: "absolute",
    bottom: 8,
    left: 3,
    color: "#000",
    fontSize: "14px",
    fontWeight: "600",
    paddingTop: 1,
    zIndex: 5,
    width: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0px 4px",
    textDecoration: "none",
    "& path": {
      boxShadow: "1px 1px 3px #000",
    },
  },
  text: {
    fontSize: "13px",
    fontWeight: "600",
    opacity: 0.6,
    textDecoration: "underline",
  },
  textStart: {
    fontSize: "13px",
    fontWeight: "600",
    opacity: 0.6,
    margin: "1px 0px 5px 0px",
    textDecoration: "underline",
  },
  gold: {
    color: "gold",
    fontSize: "20px",
    paddingBottom: 1,
  },
  ButtonContent: {
    backgroundColor: "#5DBCA3",
    color: "#fff",
    textTransform: "none",
    width: "95%",
    height: "34px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    textDecoration: "none",
    fontWeight: "700",
    fontSize: "18px",
    lineHeight: "26px",
    borderRadius:'5px',

    "&:hover": {
      color: "#fff",
    },
  },
  FooterContainer: {
    width: "98%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "5px 5px",
    margin: "3px 0px 3px 0",
    backgroundColor: "transparent",
    // backgroundColor: "#698",
  },
  RowLiv: {
    display: "flex",
    alignItems: "center",
    width: "100%",
  },
  FooterContainerLast: {
    width: "98%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "5px 5px",
    margin: "0px 0px 3px 0",
    backgroundColor: "transparent",
    cursor: "pointer",
    "&:hover": {
      color: "#237a59",
    },
  },
  divider: {
    width: "97%",
    margin: "3px 0px 3px 0",
    color: "#078",
    backgroundColor: "#698",
  },
  SpanBacg: {
    height: "5px",
    width: "90px",
    backgroundColor: "#FCD647",
    position: "absolute",
    bottom: 11,
    left: -6,
    // zIndex:10,
  },
  Vide:{
    backgroundColor: "#fff",
    height:'100%',
    width:'100%',
    display:'flex',
    justifyContent: 'center',
    color:'#5DBCA3',
    fontWeight:'700',
    fontSize:20,
    paddingTop: 200,
  }
}));
export default useStyles;
